---
- hosts: all
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "nodejs" }

  tasks:
    - name: Install Git
      apt: pkg=git state=present

    - name: Update bashrc adding font path export
      shell: echo "export MAPNIK_FONT_PATH=/vagrant/fonts" >> /home/vagrant/.bashrc

    - name: Update bashrc adding mapbox token
      shell: echo "export MAPBOX_ACCESS_TOKEN={{ mapbox_access_token }}" >> /home/vagrant/.bashrc

    - name: Install node modules
      shell: npm install -g tessera tl mbtiles mapnik  tilelive tilelive-file tilelive-http tilelive-mapbox tilelive-mapnik tilelive-s3 tilelive-tmsource tilelive-tmstyle tilelive-utfgrid tilelive-vector tilejson

    - name: Copy package.json
      copy: src=files/package.json dest=/usr/local/lib/package.json owner=root group=root mode=0644

    - name: Copy shrinkwrap file.
      copy: src=files/npm-shrinkwrap.json dest=/usr/local/lib/npm-shrinkwrap.json owner=root group=root mode=0644

    - name: Fix modules.
      shell: cd /usr/local/lib && sudo npm install

    - name: Add patched file.
      copy: src=files/index.js dest=/usr/local/lib/node_modules/tl/node_modules/tilelive-streaming/index.js
